### ISSUE TITLE
Hi and thx

### ISSUE THREAD

**Issue by kirabc** [Veids/AutoBuddy#1]
hi veids first of all i need to say thx for your work (i know you update this for your private..thx for share this) I have been using this with great success.

Suggest:
I have a suggest  for auto select lane (with this we able to go normal games with less reports)

> > put random delay with every check because is possible two or more people with same script on the match :)
> > start at bot lane (if have  2 people go to mid)
> > if mid have 1 people go to top
> > if we select adc for autoplay with this logic we can choose a lane without take a lane of someone and get alot less reports..

**Comment by Veids** [comment]
Thanks for the reply. I have updated lane selector with changes:
1. Now "Auto Select" by default start at bot lane (if have 2 pl going to mid or top)
2. Putted random delay on early selection lane (from 500ms to 5 sec)
If you have another suggestion I'm ready to listen

P.S. Sorry for English if something is wrong
